"""Git operations manager for branch lifecycle, commits, and PR automation."""

import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path

import git


def sanitize_branch_slug(text: str) -> str:
    """Convert an arbitrary string into a safe, URL/git-friendly slug."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return slug[:40] if slug else "patch"


class GitOpsManager:
    """Manages Git repository operations, branches, commits, and PR creation."""

    def __init__(self, repo_path: Path | str) -> None:
        self.repo_path = Path(repo_path).resolve()
        try:
            self.repo = git.Repo(str(self.repo_path))
        except (git.InvalidGitRepositoryError, git.NoSuchPathError) as e:
            raise ValueError(f"Path is not a valid git repository: {self.repo_path}") from e

    @property
    def current_branch(self) -> str:
        """Return the name of the currently checked out branch."""
        try:
            return str(self.repo.active_branch.name)
        except TypeError:
            return "DETACHED_HEAD"

    def create_fix_branch(self, issue_id: str, title: str | None = None) -> str:
        """Create and switch to a new fix branch for the specified issue."""
        slug = sanitize_branch_slug(title or "repair")
        safe_issue = re.sub(r"[^a-zA-Z0-9_-]+", "", issue_id) or "issue"
        branch_name = f"fix/{safe_issue}-{slug}"

        # If branch already exists, switch to it; otherwise create with -b
        existing = [b.name for b in self.repo.branches]
        if branch_name in existing:
            self.repo.git.checkout(branch_name)
        else:
            self.repo.git.checkout("-b", branch_name)

        return branch_name

    def stage_files(self, files: list[str] | None = None) -> list[str]:
        """Stage modified files or an explicit list of paths."""
        if files:
            valid_files = [f for f in files if (self.repo_path / f).exists()]
            if valid_files:
                self.repo.git.add(*valid_files)
                return valid_files

        # Stage all tracked modified and untracked files
        self.repo.git.add(A=True)
        staged_diff = self.repo.git.diff("--name-only", "--cached")
        return [f.strip() for f in staged_diff.splitlines() if f.strip()]

    def get_diff(self, staged: bool = True) -> str:
        """Get unified git diff of staged changes (or working tree if none staged)."""
        if staged:
            diff = self.repo.git.diff("--cached")
            if diff:
                return str(diff)
        return str(self.repo.git.diff())

    def commit_changes(
        self,
        issue_id: str,
        summary: str,
        description: str | None = None,
    ) -> str:
        """Create a conventional commit from currently staged changes."""
        clean_summary = summary.strip().replace("\n", " ")
        msg_parts = [f"fix({issue_id}): {clean_summary}"]
        if description:
            msg_parts.append(f"\n{description.strip()}")
        msg_parts.append("\nGenerated by Ares Autonomous Code Repair Engine")
        commit_msg = "\n".join(msg_parts)

        commit = self.repo.index.commit(commit_msg)
        return str(commit.hexsha)

    def push_branch(self, remote: str = "origin") -> None:
        """Push current active branch to the specified remote."""
        branch = self.current_branch
        self.repo.git.push("-u", remote, branch)

    def parse_github_remote(self, remote: str = "origin") -> tuple[str, str] | None:
        """Extract (owner, repo) from origin remote URL if it points to GitHub."""
        try:
            remote_url = self.repo.remotes[remote].url
        except (IndexError, KeyError, AttributeError):
            return None

        # Matches git@github.com:owner/repo.git or https://github.com/owner/repo(.git)
        pattern = r"github\.com[:/](?P<owner>[^/]+)/(?P<repo>[^/.]+)(?:\.git)?"
        match = re.search(pattern, remote_url)
        if match:
            return match.group("owner"), match.group("repo")
        return None

    def create_pull_request(
        self,
        title: str,
        body: str,
        base: str = "main",
        github_token: str | None = None,
        remote: str = "origin",
    ) -> str | None:
        """Create a GitHub Pull Request via GitHub REST API if token is configured."""
        token = github_token or os.environ.get("GITHUB_TOKEN")
        if not token:
            return None

        repo_info = self.parse_github_remote(remote)
        if not repo_info:
            return None

        owner, repo_name = repo_info
        url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls"
        head_branch = self.current_branch

        payload = {
            "title": title,
            "body": body,
            "head": head_branch,
            "base": base,
        }
        data = json.dumps(payload).encode("utf-8")
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "Ares-Code-Repair",
        }

        req = urllib.request.Request(url, data=data, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=10) as response:
                res_body = json.loads(response.read().decode("utf-8"))
                return str(res_body.get("html_url", ""))
        except (urllib.error.URLError, Exception):
            return None

    def rollback(self) -> None:
        """Revert unstaged and staged changes in the working tree."""
        self.repo.git.reset("--hard")
        self.repo.git.clean("-fd")
