"""Integration test for full CLI fix workflow with git branch and commit automation."""

from pathlib import Path
from unittest.mock import MagicMock

import git
import pytest
from typer.testing import CliRunner

from ares.cli.main import app

runner = CliRunner()


@pytest.fixture
def buggy_git_project(tmp_path: Path) -> Path:
    """Create a temporary git repository with a failing test and buggy code."""
    repo = git.Repo.init(str(tmp_path))
    repo.config_writer().set_value("user", "name", "Ares CI").release()
    repo.config_writer().set_value("user", "email", "ares-ci@test.com").release()

    calc_file = tmp_path / "calc.py"
    calc_file.write_text(
        "def add(a: int, b: int) -> int:\n    return a - b  # Buggy subtraction\n",
        encoding="utf-8",
    )

    test_file = tmp_path / "test_calc.py"
    test_file.write_text(
        "from calc import add\n\ndef test_add():\n    assert add(2, 3) == 5\n",
        encoding="utf-8",
    )

    repo.index.add(["calc.py", "test_calc.py"])
    repo.index.commit("feat: initial buggy implementation")
    return tmp_path


def test_cli_fix_end_to_end_workflow(
    buggy_git_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Verify full CLI fix invocation repairs code and creates git branch and commit."""
    calls = 0

    def mock_test_runner(command: str, repo_path: str) -> tuple[int, str, str]:
        nonlocal calls
        calls += 1
        code = (Path(repo_path) / "calc.py").read_text(encoding="utf-8")
        if "a + b" in code:
            return (0, "test_calc.py . [100%]\n1 passed in 0.05s", "")
        return (1, "AssertionError: assert -1 == 5", "")

    mock_llm = MagicMock()
    mock_llm.invoke.side_effect = [
        MagicMock(content="Root cause: subtraction used instead of addition in calc.py"),
        MagicMock(
            content=[
                {
                    "file_path": "calc.py",
                    "search_block": "    return a - b  # Buggy subtraction\n",
                    "replace_block": "    return a + b\n",
                }
            ]
        ),
    ]

    from ares.agents.graph import build_repair_graph as orig_build_repair_graph

    monkeypatch.setattr(
        "ares.agents.graph.build_repair_graph",
        lambda checkpointer=None, llm=None, test_runner=None: orig_build_repair_graph(
            checkpointer=checkpointer,
            llm=mock_llm,
            test_runner=mock_test_runner,
        ),
    )

    result = runner.invoke(
        app,
        [
            "fix",
            "Fix addition bug in calc.py",
            "--repo",
            str(buggy_git_project),
            "--issue-id",
            "101",
            "--auto-approve",
        ],
    )

    if result.exit_code != 0 and result.exception:
        import traceback

        traceback.print_exception(result.exception)
    assert result.exit_code == 0
    print("CLI OUTPUT:\n", result.stdout)
    assert "RESOLVED" in result.stdout
    assert "Created branch" in result.stdout

    repo = git.Repo(str(buggy_git_project))
    assert repo.active_branch.name == "fix/101-fix-addition-bug-in-calc-py"

    fixed_code = (buggy_git_project / "calc.py").read_text(encoding="utf-8")
    assert "return a + b" in fixed_code

    commit = repo.head.commit
    assert "fix(101):" in commit.message
    assert "Generated by Ares Autonomous Code Repair Engine" in commit.message
