"""Unit tests for GitOpsManager, branch lifecycle, commits, and diff inspection."""

import json
from pathlib import Path
from unittest.mock import MagicMock, patch

import git
import pytest

from ares.git_ops.manager import GitOpsManager, sanitize_branch_slug


@pytest.fixture
def temp_git_repo(tmp_path: Path) -> Path:
    """Create a temporary initialized git repository with an initial commit."""
    repo = git.Repo.init(str(tmp_path))
    # Configure user for commits
    repo.config_writer().set_value("user", "name", "Ares Test").release()
    repo.config_writer().set_value("user", "email", "ares@test.com").release()

    readme = tmp_path / "README.md"
    readme.write_text("# Test Repo\n", encoding="utf-8")
    repo.index.add(["README.md"])
    repo.index.commit("chore: initial commit")
    return tmp_path


def test_sanitize_branch_slug() -> None:
    """Verify branch slug sanitization for special characters and length."""
    assert sanitize_branch_slug("Fix Off-By-One Error in Loop!") == "fix-off-by-one-error-in-loop"
    assert sanitize_branch_slug("---weird___slug---") == "weird-slug"
    assert sanitize_branch_slug("") == "patch"


def test_git_ops_invalid_repo(tmp_path: Path) -> None:
    """Verify ValueError is raised when path is not a git repository."""
    non_repo = tmp_path / "not_git"
    non_repo.mkdir()
    with pytest.raises(ValueError, match="is not a valid git repository"):
        GitOpsManager(non_repo)


def test_create_fix_branch(temp_git_repo: Path) -> None:
    """Verify fix branch is created and checked out."""
    mgr = GitOpsManager(temp_git_repo)
    branch = mgr.create_fix_branch("42", "Null Pointer Exception")

    assert branch == "fix/42-null-pointer-exception"
    assert mgr.current_branch == branch


def test_create_fix_branch_existing(temp_git_repo: Path) -> None:
    """Verify switching to an existing branch if already created."""
    mgr = GitOpsManager(temp_git_repo)
    branch1 = mgr.create_fix_branch("99", "Duplicate Test")
    # Switch to main/master first
    default_branch = "master" if "master" in [b.name for b in mgr.repo.branches] else "main"
    mgr.repo.git.checkout(default_branch)

    # Re-calling create_fix_branch should switch back
    branch2 = mgr.create_fix_branch("99", "Duplicate Test")
    assert branch2 == branch1
    assert mgr.current_branch == branch1


def test_stage_files_and_get_diff(temp_git_repo: Path) -> None:
    """Verify staging changes and generating unified git diff."""
    mgr = GitOpsManager(temp_git_repo)
    # Modify an already tracked file (README.md)
    readme = temp_git_repo / "README.md"
    readme.write_text("# Updated Test Repo\n", encoding="utf-8")

    # Before staging: diff should be detected in working tree for tracked file
    unstaged_diff = mgr.get_diff(staged=False)
    assert "+# Updated Test Repo" in unstaged_diff

    # Add a new file and stage it
    code_file = temp_git_repo / "calc.py"
    code_file.write_text("def add(a, b):\n    return a - b\n", encoding="utf-8")
    staged = mgr.stage_files(["calc.py", "README.md"])
    assert "calc.py" in staged

    staged_diff = mgr.get_diff(staged=True)
    assert "+def add(a, b):" in staged_diff
    assert "+# Updated Test Repo" in staged_diff


def test_commit_changes(temp_git_repo: Path) -> None:
    """Verify structured conventional commit generation."""
    mgr = GitOpsManager(temp_git_repo)
    fix_file = temp_git_repo / "fix.txt"
    fix_file.write_text("fixed\n", encoding="utf-8")
    mgr.stage_files()

    sha = mgr.commit_changes(
        issue_id="101",
        summary="fix off-by-one error",
        description="Corrected indexing boundary in loop condition",
    )
    assert len(sha) == 40
    last_commit = mgr.repo.head.commit
    assert last_commit.hexsha == sha
    assert "fix(101): fix off-by-one error" in last_commit.message
    assert "Corrected indexing boundary" in last_commit.message
    assert "Generated by Ares Autonomous Code Repair Engine" in last_commit.message


def test_rollback(temp_git_repo: Path) -> None:
    """Verify rollback reverts unstaged and staged changes and untracked files."""
    mgr = GitOpsManager(temp_git_repo)
    readme = temp_git_repo / "README.md"
    readme.write_text("# Corrupted Content\n", encoding="utf-8")
    untracked = temp_git_repo / "trash.tmp"
    untracked.write_text("trash\n", encoding="utf-8")

    mgr.rollback()

    assert readme.read_text(encoding="utf-8") == "# Test Repo\n"
    assert not untracked.exists()


def test_parse_github_remote() -> None:
    """Verify extraction of owner and repo from various GitHub remote formats."""
    mgr = GitOpsManager.__new__(GitOpsManager)
    mgr.repo = MagicMock()

    # SSH remote
    mgr.repo.remotes = {"origin": MagicMock(url="git@github.com:Lakkyra/Ares.git")}
    assert mgr.parse_github_remote("origin") == ("Lakkyra", "Ares")

    # HTTPS remote
    mgr.repo.remotes = {"origin": MagicMock(url="https://github.com/Lakkyra/Ares.git")}
    assert mgr.parse_github_remote("origin") == ("Lakkyra", "Ares")

    # Non-github remote
    mgr.repo.remotes = {"origin": MagicMock(url="https://gitlab.com/Lakkyra/Ares.git")}
    assert mgr.parse_github_remote("origin") is None


def test_create_pull_request_no_token(temp_git_repo: Path) -> None:
    """Verify PR creation returns None when no GitHub token is present."""
    mgr = GitOpsManager(temp_git_repo)
    res = mgr.create_pull_request("fix", "body", github_token=None)
    assert res is None


def test_create_pull_request_success(temp_git_repo: Path) -> None:
    """Verify PR creation sends expected payload and parses response."""
    mgr = GitOpsManager(temp_git_repo)
    mgr.parse_github_remote = MagicMock(return_value=("org", "repo"))  # type: ignore[method-assign]

    mock_resp = MagicMock()
    mock_resp.read.return_value = json.dumps(
        {"html_url": "https://github.com/org/repo/pull/1"}
    ).encode("utf-8")
    mock_resp.__enter__.return_value = mock_resp

    with patch("urllib.request.urlopen", return_value=mock_resp):
        url = mgr.create_pull_request(
            title="fix(1): solve bug",
            body="PR body",
            github_token="ghp_fake_token",
        )
        assert url == "https://github.com/org/repo/pull/1"
